### ISSUE TITLE
内测（8月28日）——问题汇总

### ISSUE THREAD

**Issue by fangzeng01** [CareerBible/zhidian-web#3]
1，往下拖动到最后，还有更多的信息时，显示“正在加载更多”

2，建议回到第一版
![image](https://user-images.githubusercontent.com/70564404/91826386-17528e00-ec70-11ea-9c8e-09122577417f.png)

3，建议红色区域，放大至蓝色区域
![image](https://user-images.githubusercontent.com/70564404/91826773-9d6ed480-ec70-11ea-8f9f-628dd4da3507.png)

4、下翻到底卡死，多次上下滑动后，可继续下翻

5、点击“TOP”，速度太慢，设置为瞬间到顶

6、支付失败后，返回界面为哲学页面，抬头是软件工程
![image](https://user-images.githubusercontent.com/70564404/91826887-c1321a80-ec70-11ea-9c4b-5787f5291a12.png)

7、按钮不清晰，折线细
建议
图标放大
折线加粗

8、新增一键取消
![image](https://user-images.githubusercontent.com/70564404/91827030-eaeb4180-ec70-11ea-8f95-9815901e6ef6.png)

9、安卓手机，点击“对比”，后翻页对比，会出现线条消失。

10、进入加载时显示如下页面
![image](https://user-images.githubusercontent.com/70564404/91827243-284fcf00-ec71-11ea-9dd8-c7df765b6386.png)

11、不同年限数据重复
![image](https://user-images.githubusercontent.com/70564404/91827307-3c93cc00-ec71-11ea-969f-fa788b0d507f.png)

12、哲学为例，北京市薪资比长沙市平均薪资低了一半
![image](https://user-images.githubusercontent.com/70564404/91828006-318d6b80-ec72-11ea-925f-ce9d5ca406f2.png)
![image](https://user-images.githubusercontent.com/70564404/91828072-4669ff00-ec72-11ea-8d1a-4aac1992fb64.png)

**Comment by tiannanana** [comment]
1-11条前端已经解决
